philihp/openskill.js

nyc.config.js
package.json

Configures `nyc` such that it knows that only our source files are in `src/`
Configures `ava` such that only our test files match `test/**/*.test.js`

Only check coverage on src/

---

package-lock.json
package.json
src/models/bradleyTerryPart.js
src/models/plackettLuce.js
src/models/thurstonMostellerPart.js
src/util.js

In benchmarks, Ramda's functions performed faster. Easy to swap these out.
In benchmarks, transposing a 1000x1000 array took a mean of 616.506931 ms
with the transpose library. With R.transpose this took a mean of 493.4570555 ms.

Replace transpose and array-zip with Ramda

---

README.md

Github is now doing this by default for new repos. That's enough of a signal for me to move toward what will be normal in the future.

rename master to main

---

src/__tests__/rating.test.js
src/rating.js

resolves a bug if you try to init a rating at zero, which is certainly reasonable if you want your average `mu` to be centered on zero.

bug: allow mu/sigma to initialize zero

---

README.md
src/__tests__/rate.test.js
src/__tests__/rate/transition.test.js
src/__tests__/util/rankings.test.js
src/__tests__/util/reorder.test.js
src/__tests__/util/util-a.test.js
src/__tests__/util/util-sum-q.test.js
src/models/bradley-terry-full.js
src/models/bradley-terry-part.js
src/models/plackett-luce.js
src/models/thurston-mosteller-full.js
src/models/thurston-mosteller-part.js
src/rate.js
src/util.js

* Fixed some bugs with reordering, so that it also reordered the provided rank. This is important, because to properly build the rank for ties so they're reindexed at 1, they both have to be in order.
* Sends in a reindexed rank, rather than just the index of the teams which was there as a placeholder.
* Opportunity here to rewrite some stuff in a more functional, less procedural way.
* TODO: Tied rankings currently works for all models except plackettLuce... looking into this

Support for tied rankings

---

src/models/__tests__/bradley-terry-full.test.js
src/models/__tests__/bradley-terry-part.test.js
src/models/__tests__/thurston-mosteller-full.test.js
src/models/__tests__/thurston-mosteller-part.test.js
src/models/bradley-terry-full.js
src/models/bradley-terry-part.js
src/models/thurston-mosteller-full.js
src/models/thurston-mosteller-part.js
src/util.js

Providing a different gamma function seems to increase accuracy of the Thurston-Mosteller model, e.g.
```js
rate(data, {
model: 'thurstonMostellerFull',
gamma: (_, k) => 1 / k
})
```

Customizable gamma function

---

package.json

Prettier rolled up a lot of packages and configuration into one and changed to a namespaced package. This should have no impact on the library itself.

chore(deps) update prettier/eslint package and configuration

---

.github/workflows/tests.yml
src/__tests__/predict-draw.test.js
src/constants.js
src/index.js
src/predict-draw.js
src/predict-win.js
src/statistics.js
src/util.js

This comes from @daegontaven's code at https://github.com/OpenDebates/openskill.py/blob/932e5029e1f9e0cd290defb102d777a6c9bd5879/openskill/rate.py#L237-L282
Seems pretty cool! 
Had to make a call to use the native [Array.prototype.flat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat), which was only added after Node 11, or use the flat in Ramda that we already include, and figured I've (to this point) leaned toward using the native thing so I should continue to do that and Node 10 is out of EOL since last year anyway.

feature: add predictDraw

---

.github/workflows/tests.yml
src/predict-draw.js

While I prefer to use the Native stuff, I'd technically have to major version release to do that so I figure I can do this and release a minor version, then remove Node 11 support and do a major version... so here we go.

feature: use Ramda to add back Node 10 support

---

.github/workflows/tests.yml
src/__tests__/rate.test.js
src/models/__tests__/index.test.js
src/models/index.js
src/predict-draw.js

* Removes support for Node 10
* Switches over to using the native Array.flat()
* Removes a typo'ed `thurstonMosteller`, missing the e.

Remove support for Node 10

---

.github/workflows/tests.yml
package.json
src/__tests__/ordinal.test.js

Bumps a bunch of devDependencies. Only one lint issue!
Splits out linting from tests, otherwise I'd lose support for 11.x

chore: update eslint/prettier/jest

---

.github/workflows/tests.yml

Things may still work, YMMV... gonna stop testing it though, so Jest can upgrade.

remove official support for node 11,12,13

---

README.md
src/__tests__/rate.test.ts
src/models/__tests__/bradley-terry-full-series.test.ts
src/models/__tests__/bradley-terry-part-series.test.ts
src/models/__tests__/index.test.ts
src/models/__tests__/plackett-luce-series.test.ts
src/models/__tests__/thurstone-mosteller-full-series.test.ts
src/models/__tests__/thurstone-mosteller-part-series.test.ts
src/models/index.ts
src/rate.ts
src/rating.ts
src/types.ts
src/util.ts

This changes the way the user can request a different model, and also opens the door for users to experiment with models which take into account a weight from partial play, which is a common request (see #272 and #179, https://github.com/OpenDebates/openskill.py/issues/29).
Also adds a Typescript type for Gamma and Model.

feat!: change and document how models are passed in

---

eslint.config.js
package.json
src/__tests__/rate.test.ts
tsconfig.json

Eslint 9 will have a new eslint.config.js file format. This gets us there, but typescript-eslint doesn't yet support 9.

update eslint config to new flat style

---

lint-staged.config.js
package.json

eslint-plugin-prettier is no longer the preferred thing, and now it's [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) instead, and just run the two as their own step, rather than prettier inside of eslint. this is probably less fragile, idk.
also lololol wtf my lint-staged config was only globbing *.js? okay, me.

fix: lint-staged should run prettier

---

src/types.ts

no longer need to ignore no-use-before-define

fix: eslint bug with no-use-before-define no longer errors

---

package.json
src/rate.ts

I believe there's an issue with the way default exports in CJS is weird, shown with the example in https://github.com/philihp/openskill.js/issues/627#issuecomment-2237978221
I added a named export to sort-unwind, so that should work around this. If that doesn't work, I think there's a tsconfig option that can be flipped (https://www.typescriptlang.org/docs/handbook/modules/appendices/esm-cjs-interop.html), but I don't fully understand the implications of that, and another alternative would be to inline sort-unwind, but I'd prefer to keep modules smaller.

fix: bump sort-unwind to verson without default export

---

.github/workflows/tests.yml

node 22.5.0 had a problem, but 22.5.1 is now out, fixing it

build: build and lint with node 22.5.1+

---

eslint.config.js
src/__tests__/predict-draw.test.ts
src/predict-draw.ts

I think maybe #611 didn't exactly get us there. This creates some tests pulled from https://github.com/philihp/openskill.js/issues/599 and from https://openskill.me, and the Javascript library should give the same result.

fix: predictDraw should give same result as python

---

package.json

This change addresses an issue where the OpenSkill model definitions (`bradleyTerryFull`, `bradleyTerryPart`, `plackettLuce`, `thurstoneMostellerFull`, and `thurstoneMostellerPart`) were not properly exported, making them inaccessible through standard import paths. The new configuration in the `package.json` allows users to directly import these models in their projects using different module formats (ES Modules, CommonJS, and TypeScript types).
**Change Details:**
The `exports` section in the `package.json` was updated to include a dedicated path for the `models` directory:
```json
"exports": {
".": {
"require": "./dist/index.cjs",
"import": "./dist/index.js",
"types": "./dist/index.d.ts"
},
"./models": {
"require": "./dist/models/index.cjs",
"import": "./dist/models/index.js",
"types": …
```

chore(deps): add missing export for models

---

src/__tests__/ordinal.test.ts
src/constants.ts
src/ordinal.ts
src/types.ts

From the Python docs: While there is no one-to-one correspondence between Elo and OpenSkill, one standard deviation is approximately equivalent to around 200 points for an Elo rating starting at around 1500. To mimic Elo, simply set alpha to 200/sigma and target to 1500 for ordinal().

Update ordinal.ts to match Python version

---

package.json

see https://github.com/evanw/esbuild/issues/3887

fix: build warning of type export order
